filepath: ""
environments:
  default:
    values:
    - versionStream/src/fake-secrets.yaml.gotmpl
    - jx-values-jx.yaml
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
- name: jx-labs
  url: https://storage.googleapis.com/jenkinsxio-labs-private/charts
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  version: 0.0.310
  name: jxboot-helmfile-resources
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- chart: jx-labs/jenkins-x-crds
  version: 0.0.7
  name: jenkins-x-crds
  namespace: jx
  values:
  - versionStream/charts/jx-labs/jenkins-x-crds/values.yaml
- chart: jx3/jx-preview
  name: jx-preview
  namespace: jx
- chart: jenkins-x/tekton
  version: 0.0.63
  name: tekton
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/tekton/values.yaml.gotmpl
- chart: jenkins-x/lighthouse
  version: 0.0.683
  name: lighthouse
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
- chart: jenkins-x/nexus
  version: 0.1.35
  name: nexus
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/nexus/values.yaml.gotmpl
- chart: jenkins-x/chartmuseum
  version: 1.1.7
  name: chartmuseum
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/chartmuseum/values.yaml.gotmpl
templates: {}
missingFileHandler: ""
