apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        jenkins-oscar:
          repos:
            jx3-eks-terraform-vault:
              required_status_checks:
                contexts:
                - promotion-build
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config: {}
    plank: {}
    pod_namespace: jx
    postsubmits:
      jenkins-oscar/jx3-eks-terraform-vault:
      - agent: tekton
        branches:
        - master
        labels:
          aadpodidbinding: tekton-bot
        name: promotion
    presubmits:
      jenkins-oscar/jx3-eks-terraform-vault:
      - agent: tekton
        always_run: true
        context: promotion-build
        labels:
          aadpodidbinding: tekton-bot
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jenkins-oscar/jx3-eks-terraform-vault: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkins-oscar/jx3-eks-terraform-vault
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkins-oscar/jx3-eks-terraform-vault
      target_url: http://deck-jx.-jx.
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
